# Generated by Django 5.1.6 on 2025-03-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(default=None, max_length=264, null=True, upload_to='file/'),
        ),
    ]
